### PR TITLE
OR-1413 update contracts

### PR DESCRIPTION
**Pull request by nguyenzung**
Fix cannot withdraw from L2 if depositing by using L1CrossDomainMessenger for the first time
Reason: overflow in L1StandardBridge.finalizeERC20() 
Test: start running a new devnet,  cd packages/tokamak/sdk, fund token and setup .env
- Deposit: npx hardhat deposit-native-token-via-messenger --amount "5" --network devnetL1
- Withdraw:  npx hardhat withdraw-native-token --amount "2" --network devnetL1

Thank you!

### CODE REVIEW

**Comment by boohyung** [comment]
@nguyenzung Thank you very much. It works well. 

I added some code and push it. If you have some good idea, please let me know. 

* We need some L2 native token in bridge test. We can use it before bridge test for L2 native token (https://github.com/tokamak-network/tokamak-titan-canyon/pull/81/commits/54b4003f20ff92b2bf9e906b9a624a27fbee8964)
* For using .env in hardhat, we should import it to hardhat.config.ts (https://github.com/tokamak-network/tokamak-titan-canyon/pull/81/commits/4bffefab5b55e07d75faf975dd2c28c696e21841)

And, To testing withdrawals for native token, we need some TON in L2 below. The amount "5" is too low to pay txn fee. tx fee in L2 is about 0.0002 (unit: Ether)

```bash
npx hardhat withdraw-native-token --amount "2" --network devnetL1                                                                         
Setup task...
Withdraw Native token: 2
l2 native token balance in L1:  613000000000000000002
l2 native balance:  6999769458999814002
withdrawal Tx: 0x29ebf7d76e45589a0d6b418b72b8ee2c46a40902ab9e5e8b99de98ca41c04fc9  Block 10052  hash 0x29ebf7d76e45589a0d6b418b72b8ee2c46a40902ab9e5e8b99de98ca41c04fc9
l2 native balance: 6999590217999662110
Prove the message
Proved the message:  0xc490ea83ced61581887e563e00b5bf11d6a056ad5810f0a45ee47c3ce07ce6ed
l2 native token balance in L1:  613000000000000000002
Finalized message tx 0xcda36c254cb208de3382883cea23623a1af45096acb91b4e4d1058a68781b157
Finalized withdrawal
l2 native token balance in L1:  613000000000000000004
```

**Comment by nguyenzung** [comment]
> @nguyenzung Thank you very much. It works well.
> 
> I added some code and push it. If you have some good idea, please let me know.
> 
> * We need some L2 native token in bridge test. We can use it before bridge test for L2 native token ([54b4003](https://github.com/tokamak-network/tokamak-titan-canyon/commit/54b4003f20ff92b2bf9e906b9a624a27fbee8964))
> * For using .env in hardhat, we should import it to hardhat.config.ts ([4bffefa](https://github.com/tokamak-network/tokamak-titan-canyon/commit/4bffefab5b55e07d75faf975dd2c28c696e21841))
> 
> And, To testing withdrawals for native token, we need some TON in L2 below. The amount "5" is too low to pay txn fee. tx fee in L2 is about 0.0002 (unit: Ether)
> 
> ```shell
> npx hardhat withdraw-native-token --amount "2" --network devnetL1                                                                         
> Setup task...
> Withdraw Native token: 2
> l2 native token balance in L1:  613000000000000000002
> l2 native balance:  6999769458999814002
> withdrawal Tx: 0x29ebf7d76e45589a0d6b418b72b8ee2c46a40902ab9e5e8b99de98ca41c04fc9  Block 10052  hash 0x29ebf7d76e45589a0d6b418b72b8ee2c46a40902ab9e5e8b99de98ca41c04fc9
> l2 native balance: 6999590217999662110
> Prove the message
> Proved the message:  0xc490ea83ced61581887e563e00b5bf11d6a056ad5810f0a45ee47c3ce07ce6ed
> l2 native token balance in L1:  613000000000000000002
> Finalized message tx 0xcda36c254cb208de3382883cea23623a1af45096acb91b4e4d1058a68781b157
> Finalized withdrawal
> l2 native token balance in L1:  613000000000000000004
> ```

Thank you very much.
Your added feature is very helpful. I have fund token manually before. 

I will add more code to calculate gas used and print it out. It will help us see the result more clearly. 
In fact, when testing I usually use much larger number like 1ETH or 2ETH

**Comment by nguyenzung** [comment]
> > @nguyenzung Thank you very much. It works well.
> > I added some code and push it. If you have some good idea, please let me know.
> > 
> > * We need some L2 native token in bridge test. We can use it before bridge test for L2 native token ([54b4003](https://github.com/tokamak-network/tokamak-titan-canyon/commit/54b4003f20ff92b2bf9e906b9a624a27fbee8964))
> > * For using .env in hardhat, we should import it to hardhat.config.ts ([4bffefa](https://github.com/tokamak-network/tokamak-titan-canyon/commit/4bffefab5b55e07d75faf975dd2c28c696e21841))
> > 
> > And, To testing withdrawals for native token, we need some TON in L2 below. The amount "5" is too low to pay txn fee. tx fee in L2 is about 0.0002 (unit: Ether)
> > ```shell
> > npx hardhat withdraw-native-token --amount "2" --network devnetL1                                                                         
> > Setup task...
> > Withdraw Native token: 2
> > l2 native token balance in L1:  613000000000000000002
> > l2 native balance:  6999769458999814002
> > withdrawal Tx: 0x29ebf7d76e45589a0d6b418b72b8ee2c46a40902ab9e5e8b99de98ca41c04fc9  Block 10052  hash 0x29ebf7d76e45589a0d6b418b72b8ee2c46a40902ab9e5e8b99de98ca41c04fc9
> > l2 native balance: 6999590217999662110
> > Prove the message
> > Proved the message:  0xc490ea83ced61581887e563e00b5bf11d6a056ad5810f0a45ee47c3ce07ce6ed
> > l2 native token balance in L1:  613000000000000000002
> > Finalized message tx 0xcda36c254cb208de3382883cea23623a1af45096acb91b4e4d1058a68781b157
> > Finalized withdrawal
> > l2 native token balance in L1:  613000000000000000004
> > ```
> 
> Thank you very much. Your added feature is very helpful. I have fund token manually before.
> 
> I will add more code to calculate gas used and print it out. It will help us see the result more clearly. In fact, when testing I usually use much larger number like 1ETH or 2ETH

I added gas-cost-calculation in withdrawal task. Those numbers are correct.

**Review by rlgns98kr — APPROVED** [review]
Thank you very much! 😍

**Pull request merged**
