### PR TITLE
feat: change npm packages name

### PR DESCRIPTION
**Pull request by 0x6e616d**
Rename NPM packages name

### CODE REVIEW

**Comment by rlgns98kr** [comment]
Thank you very much! 😍
But I think we need the prefix in the name! (@tokamak-network/sdk -> @tokamak-network/thanos-sdk) 🙇🏼‍♂️

**Comment by 0x6e616d** [comment]
> Thank you very much! 😍 But I think we need the prefix in the name! (@tokamak-network/sdk -> @tokamak-network/thanos-sdk) 🙇🏼‍♂️

Updated. Thank you!

**Review by rlgns98kr — APPROVED** [review]
Thank you very much!

**Comment by rlgns98kr** [comment]
Oh, I saw your ticket now. I knew the situation and discussecd with @boohyung.
Thank you for your contribution. 🙇🏼‍♂️

**Review by boohyung — APPROVED** [review]
+1

**Pull request merged**
