### PR TITLE
[OR-1370] add blockheader after Dencun

### PR DESCRIPTION
**Pull request by rlgns98kr**
- add blockheader after Dencun

Thank you! 🙇🏼‍♂️

### CODE REVIEW

**Review by boohyung — APPROVED** [review]
+1
Thank you so much for your hard work.

**Comment by 0x6e616d** [comment]
Can you describe the context of this PR?

**Review by 0x6e616d — APPROVED** [review]
SGTM

**Comment by rlgns98kr** [comment]
> Can you describe the context of this PR? Oh I think this PR is related to https://github.com/ethereum-optimism/optimism/pull/7993/files
> 
> So thank for your contribution Steven!

Yes, It's correct. After Dencun, the block header added. Op-node uses op-service when it syncs L1 Blocks(it verify(comparing calculated block hash and rpc block hash) as well in the sync process). So we need some more header.

**Comment by 0x6e616d** [comment]
> > Can you describe the context of this PR? Oh I think this PR is related to https://github.com/ethereum-optimism/optimism/pull/7993/files
> > So thank for your contribution Steven!
> 
> Yes, It's correct. After Dencun, the block header added. Op-node uses op-service when it syncs L1 Blocks(it verify(comparing calculated block hash and rpc block hash) as well in the sync process). So we need some more header.

Thank your clarification, love your hard work!

**Pull request merged**
